(in-package #:cl-user)

(:include "quicklisp")
(:include "quicklisp+")

(defun :alist-remove (alist keys &key key test)
  "Remove the given `keys' from `alist'"
  (remove-if (lambda (cell) (member (car cell) keys :key key :test test))
             alist))

(:include "alert")
(:include "apropos+")
(:include "apropos-value")
(:include "cl-dot+")
(:include "fizzbuzz")
(:include "id")
(:include "indent")
(:include "int-uint")
(:include "guid")
(:include "make-project")
(:include "uiop+")
(:include "user")
(:include "package+")
(:include "place")
(:include "print-hash-table")
(:include "syntax")
