(in-package #:cl-user)

(include "quicklisp")
(include "quicklisp+")

(include "alert")
(include "apropos+")
(include "apropos-value")
(include "cl-dot+")
(include "fizzbuzz")
(include "make-project")
(include "uiop+")
(include "user")
(include "place")
(include "print-hash-table")
